Mono testni zadatak/Models/ErrorViewModel.cs
namespace Mono_testni_zadatak.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mono testni zadatak/Controllers/VehicleMakeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ProjectService.DTO_s;
using ProjectService.Entities;
using ProjectService.VehicleService;

namespace Mono_testni_zadatak.Controllers
{
    public class VehicleMakeController : Controller
    {
        private readonly IVehicleMakeService _vehicleMakeService;

        public VehicleMakeController(IVehicleMakeService service)
        {
            _vehicleMakeService = service;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, int? page )
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AbrvSortParm"] = sortOrder == "Abrv" ? "abrv_desc" : "Abrv";
            ViewData["CurrentFilter"] = searchString;

            int pageSize = 5;
            int pageNumber = (page ?? 1 );

            var makes = await _vehicleMakeService.GetAllVehicleMakes(pageNumber,pageSize,searchString,sortOrder);


            ViewData["TotalPages"] = (int)Math.Ceiling(makes.TotalCount / (double)pageSize);
            ViewData["CurrentPage"] = pageNumber;



            return View(makes.Items.ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var make = await _vehicleMakeService.GetMakeByIdAsync(id);
            if (make == null)
            {
                return NotFound();
            }

            return View(make);
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, Abrv")] VehicleMakeCreate vehicleMakeDTO)
        {
            if (ModelState.IsValid)
            {
                await _vehicleMakeService.AddVehicleMake(vehicleMakeDTO);
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleMakeDTO);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var make = await _vehicleMakeService.GetMakeByIdAsync(id);
            return View(make);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VehicleMakeResponse model)
        {
            await _vehicleMakeService.UpdateMakeAsync(model);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            await _vehicleMakeService.DeleteMakeAsync(id);
            ViewBag.Message = "Record deleted";
            return RedirectToAction(nameof(Index));
        }
    }
}

Mono testni zadatak/Controllers/VehicleModelController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProjectService.DTO_s;
using ProjectService.VehicleService;

namespace Mono_testni_zadatak.Controllers
{
    public class VehicleModelController : Controller
    {
        private readonly IVehicleModelService _vehicleModelService;
        private readonly IVehicleMakeService _vehicleMakeService;

        public VehicleModelController(IVehicleModelService vehicleModelService, IVehicleMakeService vehicleMakeService)
        {
            _vehicleModelService = vehicleModelService;
            _vehicleMakeService = vehicleMakeService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, int? page, string selectedMake)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AbrvSortParm"] = sortOrder == "Abrv" ? "abrv_desc" : "Abrv";
            ViewData["CurrentFilter"] = searchString;
            ViewData["SelectedMake"] = selectedMake;

            var makes = await _vehicleMakeService.GetAllVehicleMakes();
          
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            

            var models = await _vehicleModelService.GetAllVehicleModels(pageNumber,pageSize,searchString,sortOrder,selectedMake);

            ViewData["TotalPages"] = (int)Math.Ceiling(models.TotalCount / (double)pageSize);
            ViewData["CurrentPage"] = pageNumber;
            ViewBag.Makes = new SelectList(makes, "Id", "Name");
            
            return View(models.Items.ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var model = await _vehicleModelService.GetModelByIdAsync(id);
            
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var makes = await _vehicleMakeService.GetAllVehicleMakes();
            ViewBag.Makes = new SelectList(makes, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MakeId,Name, Abrv")] VehicleModelCreate vehicleMakeDTO)
        {
            if (ModelState.IsValid)
            {
                await _vehicleModelService.AddVehicleModel (vehicleMakeDTO);
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleMakeDTO);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var makes = await _vehicleMakeService.GetAllVehicleMakes();
            ViewBag.Makes = new SelectList(makes, "Id", "Name");
            var make = await _vehicleModelService.GetModelByIdAsync(id);
            return View(make);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VehicleModelResponse model)
        {
            await _vehicleModelService.UpdateModelAsync(model);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            await _vehicleModelService.DeleteModelAsync(id);
            ViewBag.Message = "Record deleted";
            return RedirectToAction(nameof(Index));
        }
    }
}

Mono testni zadatak/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mono_testni_zadatak</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mono_testni_zadatak.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="VehicleMake" asp-action="Index">Mono_testni_zadatak</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleMake" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleMake" asp-action="Index">VehicleMake</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleModel" asp-action="Index">Vehicle Models</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Mono_testni_zadatak - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mono testni zadatak/Views/VehicleMake/Create.cshtml
@model ProjectService.DTO_s.VehicleMakeCreate

@{
    ViewData["Title"] = "CreateVehicleMake";
}

<h1>CreateVehicleMake</h1>

<h4>VehicleMakeCreate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Abrv" class="control-label"></label>
                <input asp-for="Abrv" class="form-control" />
                <span asp-validation-for="Abrv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mono testni zadatak/Views/VehicleMake/Details.cshtml
@model ProjectService.DTO_s.VehicleMakeResponse

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>VehicleMakeResponse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Abrv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Abrv)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Mono testni zadatak/Views/VehicleMake/Edit.cshtml
@model ProjectService.DTO_s.VehicleMakeResponse

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>VehicleMakeResponse</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Abrv" class="control-label"></label>
                <input asp-for="Abrv" class="form-control" />
                <span asp-validation-for="Abrv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Mono testni zadatak/Views/VehicleMake/Index.cshtml
@model IEnumerable<ProjectService.DTO_s.VehicleMakeResponse>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Vehicle Makes</h1>

<p>
    <button class="btn btn-success" onclick="location.href='@Url.Action("Create")'">Create New</button>
</p>

<form asp-action="Index" method="get">
    <p>
        Find by name or abbreviation: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
        <input type="submit" value="Search" class="btn btn-primary" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Name", "Index", new { sortOrder = ViewData["NameSortParm"], searchString = ViewData["CurrentFilter"] })
            </th>
            <th>
                @Html.ActionLink("Abbreviation", "Index", new { sortOrder = ViewData["AbrvSortParm"], searchString = ViewData["CurrentFilter"] })
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Abrv)
                </td>
                <td>
                    @{
                        var editUrl = Url.Action("Edit", new { id = item.Id });
                        var detailsUrl = Url.Action("Details", new { id = item.Id });
                        var deleteUrl = Url.Action("Delete", new { id = item.Id });
                    }

                    <!-- Buttons -->
                    <button class="btn btn-primary" onclick="location.href='@editUrl'">Edit</button>
                    <button class="btn btn-info" onclick="location.href='@detailsUrl'">Details</button>
                    <button class="btn btn-danger" onclick="if(confirm('Are you sure you want to delete this item?')) location.href='@deleteUrl'">Delete</button>
                </td>
            </tr>
        }
    </tbody>
</table>
<nav aria-label="Page navigation">
    <ul class="pagination">
        @for (int i = 1; i <= (int)ViewData["TotalPages"]; i++)
        {
            <li class="page-item @(i == (int)ViewData["CurrentPage"] ? "active" : "")">
                <a class="page-link" href="?sortOrder=@ViewData["NameSortParm"]&searchString=@ViewData["CurrentFilter"]&selectedMake=@ViewData["SelectedMake"]&page=@i">@i</a>
            </li>
        }
    </ul>
</nav>

Mono testni zadatak/Views/VehicleModel/Create.cshtml
@model ProjectService.DTO_s.VehicleModelCreate

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>VehicleModelCreate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MakeId" class="control-label"></label>
                <select asp-for="MakeId" class="form-control" asp-items="ViewBag.Makes">
                    <option value="">Select Make</option>
                </select>
                <span asp-validation-for="MakeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Abrv" class="control-label"></label>
                <input asp-for="Abrv" class="form-control" />
                <span asp-validation-for="Abrv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Mono testni zadatak/Views/VehicleModel/Details.cshtml
@model ProjectService.DTO_s.VehicleModelResponse

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>VehicleModelResponse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            Vehicle Make
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleMake.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Abrv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Abrv)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Mono testni zadatak/Views/VehicleModel/Edit.cshtml
@model ProjectService.DTO_s.VehicleModelResponse

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>VehicleModelResponse</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MakeId" class="control-label"></label>
                <select asp-for="MakeId" class="form-control" asp-items="ViewBag.Makes">
                    <option value="">Select Make</option>
                </select>
                <span asp-validation-for="MakeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Abrv" class="control-label"></label>
                <input asp-for="Abrv" class="form-control" />
                <span asp-validation-for="Abrv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Mono testni zadatak/Views/VehicleModel/Index.cshtml
@model IEnumerable<ProjectService.DTO_s.VehicleModelResponse>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <button class="btn btn-success" onclick="location.href='@Url.Action("Create")'">Create New</button>
</p>

<form asp-action="Vehicle Models" method="get">
    <p>
        Find by name or abbreviation: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
        <select name="selectedMake" asp-items="ViewBag.Makes">
            <option value="">All Makes</option>
        </select>
        <input type="submit" value="Search" class="btn btn-primary" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Name", "Index", new { sortOrder = ViewData["NameSortParm"], searchString = ViewData["CurrentFilter"], selectedMake = ViewData["SelectedMake"] })
            </th>
            <th>
                @Html.ActionLink("Abbreviation", "Index", new { sortOrder = ViewData["AbrvSortParm"], searchString = ViewData["CurrentFilter"], selectedMake = ViewData["SelectedMake"] })
            </th>
            <th>
                Makes
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Abrv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VehicleMake.Name)
                </td>
                <td>
                    @{
                        var editUrl = Url.Action("Edit", new { id = item.Id });
                        var detailsUrl = Url.Action("Details", new { id = item.Id });
                        var deleteUrl = Url.Action("Delete", new { id = item.Id });
                    }

                    <!-- Buttons -->
                    <button class="btn btn-primary" onclick="location.href='@editUrl'">Edit</button>
                    <button class="btn btn-info" onclick="location.href='@detailsUrl'">Details</button>
                    <button class="btn btn-danger" onclick="if(confirm('Are you sure you want to delete this item?')) location.href='@deleteUrl'">Delete</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<nav aria-label="Page navigation">
    <ul class="pagination">
        @for (int i = 1; i <= (int)ViewData["TotalPages"]; i++)
        {
            <li class="page-item @(i == (int)ViewData["CurrentPage"] ? "active" : "")">
                <a class="page-link" href="?sortOrder=@ViewData["NameSortParm"]&searchString=@ViewData["CurrentFilter"]&selectedMake=@ViewData["SelectedMake"]&page=@i">@i</a>
            </li>
        }
    </ul>
</nav>